DROP DATABASE IF EXISTS [ADD HERE] ;
CREATE DATABASE [ADD HERE] 
-- DROP TABLE IF EXISTS [ADD HERE] ;
-- DROP TABLE IF EXISTS [ADD HERE] ;



CREATE TABLE [ADD HERE]  (
  id SERIAL PRIMARY KEY,
  [ADD HERE]  TEXT NOT NULL,
  
);

CREATE TABLE [ADD HERE] (
  id SERIAL PRIMARY KEY,
 [ADD HERE]  TEXT NOT NULL,
  FOREIGN KEY ([ADD HERE])
  REFERENCES [ADD HERE] ([ADD HERE] 
  ON DELETE SET NULL
);

CREATE TABLE [ADD HERE] (
  id SERIAL PRIMARY KEY,
 [ADD HERE]  TEXT NOT NULL,
  FOREIGN KEY ([ADD HERE])
  REFERENCES [ADD HERE] ([ADD HERE] 
  ON DELETE SET NULL
);