INSERT INTO [ADD HERE] ([ADD HERE] )
VALUES [ADD HERE] 
	   
INSERT INTO [ADD HERE] ([ADD HERE] )
VALUES [ADD HERE] 
       
INSERT INTO [ADD HERE] ([ADD HERE] )
VALUES [ADD HERE] 

       
INSERT INTO [ADD HERE] ([ADD HERE] )
INSERT INTO [ADD HERE] ([ADD HERE] )
VALUES [ADD HERE] 